Mac Support
GamesRightMeow/playbit pull request #5
Opened 2022-09-01 16:42 UTC by notpeter

With these changes I was able to get [https://github.com/GamesRightMeow/playbit-template](playbit-template) to correct build on MacOS for both Love2D and Playdate targets. (see screenshots)

<img width="478" alt="image" src="https://user-images.githubusercontent.com/145113/187966863-a846549e-8789-47d3-a598-605372986c7a.png">
<img width="400" alt="image" src="https://user-images.githubusercontent.com/145113/187966919-109389e1-2e26-4961-b833-2565c7bf3f8e.png">

I believe I have preserved Windows/Linux support, but as I do not have a Windows or Linux desktop handy please verify that before merging.

2022-09-02 15:40 UTC, gingerbeardman commented
Can confirm this builds on macOS:

Some additional things I needed to do:
1. adjust aseprite path for my self-built version
   - `/Applications/Aseprite.app/aseprite`
2. run the Playdate compiler afterwards to generate the pdx 
   - `pdc _pdx game.pdx`

2022-09-03 06:02 UTC, SHiLLySiT commented
Ah yay, I'm so happy this was the first PR from the community! I know many people are on Macs :) 

I'll review, test, and merge this soon!

2022-09-03 13:43 UTC, notpeter commented
https://github.com/GamesRightMeow/playbit/pull/5/commits/a778914e714674ed714647fdc89b2b2c312c9e65 Fix to support multiple `/Applications/Aesprite.app` bundle formats. (cc: @gingerbeardman)

2022-09-08 21:21 UTC, SHiLLySiT requested changes

2022-09-08 21:21 UTC, SHiLLySiT commented on tools/filesystem.lua
> +    if package.config:sub(1,1) == '\\' then
This seems like it should work, but I'll need to double check when I have access to my Windows machine in 2 weeks.

2022-09-08 21:21 UTC, SHiLLySiT commented on tools/filesystem.lua
> +  assert(path ~= "/", "Not gonna recursively delete /. Giving up.")
💯

2022-09-08 21:21 UTC, SHiLLySiT commented on tools/filesystem.lua
> +      local uname, _ = run("uname -s")
Since we're not using the return code, let's not create a var for it:
```suggestion
      local uname = run("uname -s")
```

2022-09-08 21:21 UTC, SHiLLySiT commented on tools/filesystem.lua
> +      run("which greadlink", "GNU readlink not found. Install with: brew install coreutils")
@notpeter Is there another way to accomplish this on Mac without installing a non-native tool? I'd like to keep dependencies to a minimum, but if there's not another way to do this natively, this should also be added to the docs, specifically [Required software](https://github.com/GamesRightMeow/playbit/blob/main/docs/getting-started.md#required-software).

2022-09-08 21:38 UTC, SHiLLySiT commented
>     2. run the Playdate compiler afterwards to generate the pdx
>        
>        * `pdc _pdx game.pdx`
>        * not sure why this easy step is not already included?

@gingerbeardman The build script is intended to build the _projects files_ (strip platform specific code from lua, convert assets, etc) for each platform (Love2d or Playdate) and not the _final binaries_. This keeps the workflow more flexible and maintainable as we don't need to re-expose options from either options compilers.

With that said, in the [playbit-template](https://github.com/GamesRightMeow/playbit-template), I've included [tasks.json](https://github.com/GamesRightMeow/playbit-template/blob/main/.vscode/tasks.json) which contains a task for compiling the binary. So all you have to do is run the `buildRunSimulator` task to both build, compile, and run for Playdate 🙂

2022-09-15 20:16 UTC, notpeter commented on tools/filesystem.lua
> +      run("which greadlink", "GNU readlink not found. Install with: brew install coreutils")
The BSD readlink in MacOS 12.3 (March 2022) adds support for `-f` so you could check that instead (by parsing `sw_vers -productVersion`), but I'm still on Big Sur.

Alternatively we could use python:
```
python3 -c 'import pathlib; import sys; print(pathlib.Path(sys.argv[1]).resolve())' /whatever/path
```

2022-09-15 20:23 UTC, notpeter commented on build.lua
> +  end
Sure, that's why I have the check with `which`.  Since Aseprite is primarily a GUI app, the CLI bin is contained within the app bundle; a user normally has to manually add that to their path for `aseprite` to work on the CLI.  This is ugly, but I was trying to make it work no matter `aseprite` lives without forcing a user to edit their path.

2022-09-26 20:26 UTC, SHiLLySiT commented on tools/filesystem.lua
> +    if package.config:sub(1,1) == '\\' then
Just tested, and confirmed this still works 🎉

2022-09-26 20:48 UTC, SHiLLySiT requested changes
@notpeter Just two more changes, and we can get this merged!

2022-09-26 20:48 UTC, SHiLLySiT commented on build.lua
> +  end
@notpeter 

> Sure, that's why I have the check with which. 

Ah sorry, wasn't familiar with the `which` command but just looked it up 👍

> Since Aseprite is primarily a GUI app, the CLI bin is contained within the app bundle; a user normally has to manually add that to their path for aseprite to work on the CLI. This is ugly, but I was trying to make it work no matter aseprite lives without forcing a user to edit their path.

The intended behavior/design is that users _should_ edit their path for Aseprite to work. However, I recognize this isn't ideal for everyone. I'm on board with adding alternatives, but I don't think this is necessary for general Mac build support, so let's move this into a separate PR. That way we can also add the same functionality to Windows and Linux to keep feature parity across all platforms. Added #6 to capture this.

```suggestion
```

2022-09-26 20:48 UTC, SHiLLySiT commented on tools/filesystem.lua
> +      run("which greadlink", "GNU readlink not found. Install with: brew install coreutils")
@notpeter Oof yeah this is a hard one. I also realized homebrew is not pre-installed on Mac either, so that's two dependencies users will have to install. Most developers can probably figure this out, but I was trying to keep it as simple as possible as many Playdate developers are new to software development in general.

It looks like Python has been [pre-installed on Mac for awhile](https://apple.stackexchange.com/questions/264056/is-python-pre-installed-on-every-mac-version). Let's go with this method! Do you mind implementing and testing this?

2022-10-02 17:19 UTC, notpeter commented on build.lua
> +  end
I personally don't add random application bundles to my PATH so that's a dealbreaker for me. Sadly aliases are not supported by `io.open` and aseprite refuses to launch from a symlink, so neither of these work:
```
alias aseprite="$(find /Applications/Aseprite.app -name aseprite)"
ln -s "$(find /Applications/Aseprite.app -name aseprite)" /usr/local/bin/aseprite
```

Guess this is one of the huge downsides for using lua for shell scripting...you can't support basic configurations like aliases. This code works out of the box with aseprite on Linux and on MacOS (with both Open Source and Official apps bundles) feel free to delete it if you'd prefer it be broken by default.

2022-10-02 17:20 UTC, notpeter commented on tools/filesystem.lua
> +      run("which greadlink", "GNU readlink not found. Install with: brew install coreutils")
Switched to using python to emulate `greadlink -f` on MacOS in a30bacc1268772575cbe1756b9df4f2bd8973a4f.

2022-10-02 17:25 UTC, notpeter commented
I dropped the greadlink requirement and left the aseprite magic, feel free to resolve the PR as you see fit. I'm not gonna make further changes.

2022-10-04 20:59 UTC, merged

2022-10-04 20:59 UTC, SHiLLySiT commented
@notpeter Thanks for all your work!